version: '3'
services:
  test-gcc:
    build:
      context: ./
    volumes:
      - ./source:/root/source
    working_dir: /root/source
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
